### ISSUE TITLE
Fantastic list!

### ISSUE THREAD

**Issue by Tomas0413** [godmoves/reinforcement_learning_collections#1]
Hi, @godmoves , I discovered your GitHub repo yesterday - it looks great, thanks for creating such a list and sharing it!

I also wanted to ask if you think Microsoft's Project Malmo belongs to this list. 
"Project Malmo is a platform for Artificial Intelligence experimentation and research built on top of Minecraft."
https://github.com/microsoft/malmo 

P.S. I don't work for Microsoft.

**Comment by godmoves** [comment]
Thank you for your recommendation!
Malmo is a great project but it is more like a platform rather than an implementation of DRL algorithms. So I don't think we need to include it into this list.
